Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 15
Rules claiming more threads will be scaled down.
Job stats:
job             count
------------  -------
all                 1
conf_factors        1
suppl_files         1
total               3

Select jobs to execute...

[Thu Jul  4 20:01:24 2024]
rule conf_factors:
    input: deconv_analysis_fig2_3fig4_2_3_6_9.html
    output: conf_factors_fig4_7.html
    jobid: 7
    reason: Missing output files: conf_factors_fig4_7.html
    resources: tmpdir=/tmp

[Thu Jul  4 20:01:24 2024]
rule suppl_files:
    input: deconv_analysis_fig2_3fig4_2_3_6_9.html, deconv_analysis_fig2_3fig4_2_3_6_9.html, bio_insights_fig4_4_5.html
    output: suppl_files1_4_5.html
    jobid: 1
    reason: Missing output files: suppl_files1_4_5.html
    resources: tmpdir=/tmp

[Thu Jul  4 20:01:33 2024]
Error in rule suppl_files:
    jobid: 1
    input: deconv_analysis_fig2_3fig4_2_3_6_9.html, deconv_analysis_fig2_3fig4_2_3_6_9.html, bio_insights_fig4_4_5.html
    output: suppl_files1_4_5.html

RuleException:
CalledProcessError in file /data/fass5/projects/aram/current_projects/phd_tests/Chapter 4/snakemake_pipeline, line 65:
Command 'set -euo pipefail;  Rscript --vanilla -e 'rmarkdown::render("/data/fass5/projects/aram/current_projects/phd_tests/Chapter 4/.snakemake/scripts/tmp10cmglu_.suppl_files1_4_5.Rmd", output_file="/data/fass5/projects/aram/current_projects/phd_tests/Chapter 4/suppl_files1_4_5.html", quiet=TRUE, knit_root_dir = "/data/fass5/projects/aram/current_projects/phd_tests/Chapter 4", params = list(rmd="/data/fass5/projects/aram/current_projects/phd_tests/Chapter 4/.snakemake/scripts/tmp10cmglu_.suppl_files1_4_5.Rmd"))'' returned non-zero exit status 1.
  File "/data/fass5/projects/aram/current_projects/phd_tests/Chapter 4/snakemake_pipeline", line 65, in __rule_suppl_files
  File "/home/si48met/miniconda3/envs/cfdeconv_lc/lib/python3.10/concurrent/futures/thread.py", line 58, in run
[Thu Jul  4 20:01:35 2024]
Error in rule conf_factors:
    jobid: 7
    input: deconv_analysis_fig2_3fig4_2_3_6_9.html
    output: conf_factors_fig4_7.html

RuleException:
CalledProcessError in file /data/fass5/projects/aram/current_projects/phd_tests/Chapter 4/snakemake_pipeline, line 55:
Command 'set -euo pipefail;  Rscript --vanilla -e 'rmarkdown::render("/data/fass5/projects/aram/current_projects/phd_tests/Chapter 4/.snakemake/scripts/tmpzww9zabo.conf_factors_fig4_7.Rmd", output_file="/data/fass5/projects/aram/current_projects/phd_tests/Chapter 4/conf_factors_fig4_7.html", quiet=TRUE, knit_root_dir = "/data/fass5/projects/aram/current_projects/phd_tests/Chapter 4", params = list(rmd="/data/fass5/projects/aram/current_projects/phd_tests/Chapter 4/.snakemake/scripts/tmpzww9zabo.conf_factors_fig4_7.Rmd"))'' returned non-zero exit status 1.
  File "/data/fass5/projects/aram/current_projects/phd_tests/Chapter 4/snakemake_pipeline", line 55, in __rule_conf_factors
  File "/home/si48met/miniconda3/envs/cfdeconv_lc/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-07-04T200122.959062.snakemake.log
